<?php


namespace Bedivierre\Alfastrah\Requests\KBM;


use Bedivierre\Alfastrah\AS_API;
use Bedivierre\Alfastrah\AS_Config;
use Bedivierre\Alfastrah\Data\JuridicalData;
use Bedivierre\Alfastrah\Requests\BaseRequest;
use Bedivierre\Alfastrah\Responses\BaseResponse;
use Bedivierre\Alfastrah\Responses\KBM\KBMJuridicalResponse;
use Bedivierre\Craftsman\Aqueduct\BaseResponseObject;
use Bedivierre\Craftsman\Masonry\BaseDataObject;

/**
 * Class KBM_JuridicalRequest
 * @package Bedivierre\Alfastrah\Requests\KBM
 * @property JuridicalData $organization
 */
class KBMJuridicalRequest extends BaseRequest
{
    public function __construct(string $name, string $inn, bool $rf_resident = true, $testmode = null)
    {
        parent::__construct(AS_API::$kbm_juridical, 'post', $testmode);
        $this->organization = new JuridicalData($name, $inn, $rf_resident);
    }

    /**
     * @param array $data
     * @return BaseResponseObject|BaseResponse|KBMJuridicalResponse
     */
    public function doRequest($data = [])
    {
        return parent::doRequest($data); // TODO: Change the autogenerated stub
    }
}