<?php


namespace Bedivierre\Alfastrah\Requests\KBM;


use Bedivierre\Alfastrah\AS_API;
use Bedivierre\Alfastrah\AS_Config;
use Bedivierre\Alfastrah\Data\JuridicalData;
use Bedivierre\Alfastrah\Data\PersonDataBlock;
use Bedivierre\Alfastrah\Data\PersonDocument;
use Bedivierre\Alfastrah\Requests\BaseRequest;
use Bedivierre\Alfastrah\Responses\BaseResponse;
use Bedivierre\Alfastrah\Responses\KBM\KBMJuridicalResponse;
use Bedivierre\Alfastrah\Responses\KBM\KBMPhysicalResponse;
use Bedivierre\Craftsman\Aqueduct\BaseResponseObject;
use Bedivierre\Craftsman\Masonry\BaseDataObject;

/**
 * Class KBM_JuridicalRequest
 * @package Bedivierre\Alfastrah\Requests\KBM
 * @property PersonDataBlock[] $persons
 */
class KBMPhysicalRequest extends BaseRequest
{
    public function __construct(string $name, string $inn, bool $rf_resident = true, $testmode = null)
    {
        parent::__construct(AS_API::$kbm_physical, 'post', $testmode);
        $this->persons = new BaseDataObject();
        $this->addRequirement('persons', 'bdo');
    }

    public function addPerson(PersonDataBlock $dataBlock){
        $this->persons[] = $dataBlock;
    }


    /**
     * @param array $data
     * @return BaseResponseObject|BaseResponse|KBMPhysicalResponse
     */
    public function doRequest($data = [])
    {
        return parent::doRequest($data); // TODO: Change the autogenerated stub
    }
}